### ISSUE TITLE
No output file found

### ISSUE THREAD

**Issue by m0binasadi** [AbhishekSalian/Video2Images#3]
![Screenshot (410)](https://user-images.githubusercontent.com/76769509/133399119-b9ac8358-d654-4a17-962b-2a87026ed1d3.png)

**Comment by AbhishekSalian** [comment]
Try to give the full path of the folder for e.g C:\......\video

**Comment by m0binasadi** [comment]
**code:**

`from video2images import Video2Images

Video2Images(video_filepath=r"H:\test_p\venv\pic\wkk.mp4",out_dir=r"H:\test_p\venv\video")`


**Error:**
Traceback (most recent call last):
  File "H:\test_p\venv\retye.py", line 4, in <module>
    Video2Images(video_filepath=r"H:\test_p\venv\pic\wkk.mp4",out_dir=r"H:\test_p\venv\video")
  File "c:\users\pardaz_rayan\appdata\local\programs\python\python39\lib\site-packages\video2images\video2images.py", line 96, in __init__
    os.mkdir(self.out_dir + os.path.sep + folder_name)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'H:\\test_p\\venv\\video\\frames_folder_2021-09-15 13:18:31'

**Comment by m0binasadi** [comment]
> Try to give the full path of the folder for e.g C:......\video

I entered the full address but it still has an error

**Comment by AbhishekSalian** [comment]
If you want the output on an immediate basis don't enter any out_dir path (follow below code) till then I can find out the solution for this issue
`from video2images import Video2Images

Video2Images(video_filepath=r"H:\test_p\venv\pic\wkk.mp4")`

Let me know if this too doesn't work. Thanks

**Comment by AbhishekSalian** [comment]
The output folder will be automatically created in the current working directory if we don't provide any out_dir path

**Comment by m0binasadi** [comment]
> The output folder will be automatically created in the current working directory if we don't provide any out_dir path

I tried but again I got an error☹

**Comment by AbhishekSalian** [comment]
Same error?

**Comment by m0binasadi** [comment]
> Same error?

yeah !!!

**Comment by m0binasadi** [comment]
> Same error?

I solved this problem, but I changed the original code
